### ISSUE TITLE
not able to google sign in

### ISSUE THREAD

**Issue by HaardikBhagtani** [KalleHallden/exer_log#29]
```
E/flutter ( 6690): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter ( 6690): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 6690): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 6690): <asynchronous suspension>
E/flutter ( 6690): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
E/flutter ( 6690): <asynchronous suspension>
E/flutter ( 6690): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:248:30)
E/flutter ( 6690): <asynchronous suspension>
E/flutter ( 6690): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:378:5)
E/flutter ( 6690): <asynchronous suspension>
E/flutter ( 6690): 
```
Getting this error when trying to google sign in.
As mentioned in this [stackoverflow answer](https://stackoverflow.com/a/66660098/19075143), we need to add debug SHA-1 keys of developers to the firebase project. How can that be done?

**Comment by Scount** [comment]
@HaardikBhagtani This is a duplicate of #14. Adding the SHA-1 key can only be done by @KalleHallden because he is the only one with access to the firebase project. I would suggest to close this issue and continue with #14.

**Comment by HaardikBhagtani** [comment]
closing this issue because it is duplicate #14

**Comment by HaardikBhagtani** [comment]
closing this issue because it is duplicate #14
